### ISSUE TITLE
Preview of Sketch symbols rendering too small

### ISSUE THREAD

**Issue by tidimedia** [amccloud/storybook-addons-abstract#17]
We're getting some Sketch symbols rendered in the preview pane in Storybook that aren't their native size, but are shrunk down. There doesn't seem to be anything different in the original Sketch files between the symbols that are affected and those that aren't. It's proving difficult to do first glance QA using Storybook which was the primary reason for implementing Abstract. Any ideas?

**Comment by amccloud** [comment]
@tidimedia thanks for the report. This is a known issue with Sketch exporting previews for symbols with overrides that are not on artboards 

I was actually looking into this yesterday and I think may have a workaround. Would your mind sharing an Abstract share link to one of your symbols that embeds incorrectly so that I can confirm?

**Comment by tidimedia** [comment]
Hi, yep, https://app.abstract.com/share/ccab3a21-7267-48b8-ad3d-22d14d9ade9c?collectionLayerId=bcbe7055-8646-4907-8180-451fd1499bf0 is one instance of an element previewing smaller than its native dimensions. Thanks for the assist.

**Comment by amccloud** [comment]
Hey @tidimedia thanks for the report and details

Quick update, I've reported this issue to the team that works on the embed and they are looking into it. Since this is an issue with the embed and not the addon I'll keep this ticket closed and ping you once the embed is fixed

Sorry about the noisy stale bot. This is a new repo and I'm still tuning our ticket triage process
