### ISSUE TITLE
support for app domain -> https://app.abstract.com domain is not allowed in the plugin

### ISSUE THREAD

**Issue by vijay122** [amccloud/storybook-addons-abstract#31]
recently, abstract is internally routing all the https://share.abstract domains to https://app.abstract domains. but the plugin is not allowing the https://app.abstract.com domains. below is the error while compiling the storybook.

The url must come from "https://share.abstract.com/" or "https://share.goabstract.com/"

can you check this to remove or add the app domain, it would be helpful to use the functionality what it is built for.

**Comment by amccloud** [comment]
Heya @vijay122 thanks for the feedback

share.abstract.com is intentional canonical link that will never break or change even if the abstract app changes routes. Anywhere you can copy a link from Abstract will be a share url

This is intentional design decision at the moment. We won’t be able to support app.abstract.com until the abstract sdk exposes more public api
