### ISSUE TITLE
Uncaught Error: Element type is invalid

### ISSUE THREAD

**Issue by maeligg** [amccloud/storybook-addons-abstract#4]
Hello,

I'm getting the following error with the code provided in the documentation :
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

I'm using React 16.6.0, @storybook/react 5.1.9 and storybook-addons-abstract 5.0.3. Any idea what might be causing this problem ?

**Comment by amccloud** [comment]
Hey @maeligg 👋 

Thanks for the report. I've seen this error before and I think it's a common mistake in react projects. It usually happens when one of the variables you're using in JSX is not a valid element

Somewhere you must be passing `undefined` to JSX. That's likely caused by a bad import path or missing export for one of your components

**Comment by jin-chen-narvar** [comment]
I had the same error and upgrading to ` @storybook/react` to `5.2.X` solved it for me

**Comment by amccloud** [comment]
@jin-chen-narvar thanks for that tip! The example in this repo and my own storybook setup also uses `5.2.x`

I wonder what changed from `5.1.x` that could cause this and if it impacts other addons 🤔

**Comment by maeligg** [comment]
Thanks @jin-chen-narvar ! Indeed, updating @storybook/react to 5.2.0 fixed the issue. I think it's part of the API changes they rolled out in this version. Maybe useful to add this info in the readme.
